services:
    liker_stream_processor_deduplicator:
        build:
            context: .
            dockerfile: Dockerfile
        command: sleep infinity
        volumes:
            - ./:/workspace
    adminer:
        image: adminer
        depends_on:
            - db
        restart: always
        ports:
            - ${LIKER_STREAM_PROCESSOR_DEDUPLICATOR_ADMINER_HOST_PORT}:8080
networks:
    default:
        external: true
        name: "liker"
